### ISSUE TITLE
i am getting this error while building 

### ISSUE THREAD

**Issue by ghost** [RivaanRanawat/flutter-zoom-clone#2]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jitsi_meet:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by gajzzs** [comment]
Refer to [this](https://stackoverflow.com/questions/72412564/jitsimeetplugin-kt-66-42-type-mismatch-inferred-type-is-activity-but-acti), if the error is same as in my case then it will work! As you haven't provided enough logs.

**Comment by ghost** [comment]
@coderscoding  ty for this.. it made it !!
